### ISSUE TITLE
(BUG) [DrawingForKids Current Version 8.0 ] The application automatically opens after two or three seconds

### ISSUE THREAD

**Issue by XAMIR555** [jmalenko/DrawingForKids#3]
#### Project Information
* Repository---------------:[Here](https://github.com/jmalenko/DrawingForKids)
* Project Name------------: [DrawingForKids](https://play.google.com/store/apps/details?id=cz.jaro.drawing)
* Publisher-----------------: [Jaromír Malenko jmalenko](https://github.com/jmalenko)
* My GitHub account------:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When I close the application, the application should not open automatically after closing, but when I open the application, then the application should be open.

#### Actual behavior

When I wait two or three seconds on the mobile screen home page, the application automatically opens and the application opens when I try to uninstall the application.

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=cz.jaro.drawing) 
* open the application
* Close the app and wait for one second or 3 seconds on the mobile home screen
* You will see that the application automatically opens
* Note the Bug

* Browser/App version-: Current Version 8.0
* Operating system----: 9.0.0

#### Recording Of The Bug

![20190529_211412](https://user-images.githubusercontent.com/49812927/58574942-0528ab00-81f6-11e9-8cf3-0db47b44a9ab.gif)

# The application automatically opens when I try to uninstall the application

![20190529_211257](https://user-images.githubusercontent.com/49812927/58575984-238fa600-81f8-11e9-83ba-a931fbb4521d.gif)

**Comment by jmalenko** [comment]
This is intentional.
The motivation for this app is to remain in the drawing app whatever happens. When the kid is drawing, there are many options to interact with the android system, leaving the app is such an interaction. The interactions with the android system are undesirable and thus the app resumes.
In your report, the uninstall is not possible because before the uninstall dialog is displayed, the drawing activity is brought to foreground. First quit the app(via the notification) and then you can uninstall.
